[book]
authors = ["Eddy (Eduard) Stefes"]
language = "en"
multilingual = false
src = "src"
title = "a fabulous world"

[build]
build-dir = "docs" 

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
